#cloud-config
package_update: true
package_upgrade: true
packages:
  - python3
  - python3-pip
  - python3-venv
  - systemd
  - supervisor
runcmd:
  - [bash, -lc, 'if [ -d /root/gipsr_bot ]; then cd /root/gipsr_bot && bash scripts/autodeploy.sh; else echo "[gipsr_bot] Папка /root/gipsr_bot не найдена. Загрузите проект через FileZilla и перезагрузите сервер." >&2; fi']
