#cloud-config
package_update: true
package_upgrade: true
packages:
  - python3
  - python3-pip
  - python3-venv
  - systemd
write_files:
  - path: /etc/systemd/system/gipsrbot-autodeploy.service
    owner: root:root
    permissions: '0644'
    content: |
      [Unit]
      Description=GIPSR Bot auto deployment
      After=network-online.target
      Wants=network-online.target
      ConditionPathExists=/root/gipsr_bot/scripts/autodeploy.sh

      [Service]
      Type=oneshot
      WorkingDirectory=/root/gipsr_bot
      Environment=GIPSRBOT_APP_DIR=/root/gipsr_bot
      ExecStart=/bin/bash /root/gipsr_bot/scripts/autodeploy.sh
      StandardOutput=journal
      StandardError=journal

      [Install]
      WantedBy=multi-user.target
  - path: /etc/systemd/system/gipsrbot-autodeploy.path
    owner: root:root
    permissions: '0644'
    content: |
      [Unit]
      Description=Trigger GIPSR Bot deployment when files arrive

      [Path]
      PathExists=/root/gipsr_bot/scripts/autodeploy.sh
      PathExists=/root/gipsr_bot/.env
      PathChanged=/root/gipsr_bot/.env
      PathModified=/root/gipsr_bot/.env
      PathChanged=/root/gipsr_bot/bot.py
      PathModified=/root/gipsr_bot/bot.py
      PathChanged=/root/gipsr_bot/requirements.txt
      PathModified=/root/gipsr_bot/requirements.txt
      PathChanged=/root/gipsr_bot/scripts/autodeploy.sh
      PathModified=/root/gipsr_bot/scripts/autodeploy.sh
      PathChanged=/root/gipsr_bot/scripts/gipsrbot-bot.service
      PathModified=/root/gipsr_bot/scripts/gipsrbot-bot.service
      PathExists=/root/gipsr_bot/data
      PathChanged=/root/gipsr_bot/data/prices.json
      PathModified=/root/gipsr_bot/data/prices.json
      PathChanged=/root/gipsr_bot/data/orders.json
      PathModified=/root/gipsr_bot/data/orders.json
      PathChanged=/root/gipsr_bot/data/user_logs.json
      PathModified=/root/gipsr_bot/data/user_logs.json
      PathChanged=/root/gipsr_bot/data/users.json
      PathModified=/root/gipsr_bot/data/users.json
      PathChanged=/root/gipsr_bot/data/referrals.json
      PathModified=/root/gipsr_bot/data/referrals.json
      PathChanged=/root/gipsr_bot/data/feedbacks.json
      PathModified=/root/gipsr_bot/data/feedbacks.json
      PathChanged=/root/gipsr_bot/data/bonuses.json
      PathModified=/root/gipsr_bot/data/bonuses.json
      Unit=gipsrbot-autodeploy.service

      [Install]
      WantedBy=multi-user.target
runcmd:
  - [mkdir, -p, /root/gipsr_bot]
  - [systemctl, daemon-reload]
  - [systemctl, enable, '--now', 'gipsrbot-autodeploy.path']
  - [systemctl, start, 'gipsrbot-autodeploy.service']
